### ISSUE TITLE
[notification][variables][visual-tracking] Android app fails to build when referencing Android modules with wrong dependency resolution

### ISSUE THREAD

**Issue by wasnot** [plaidev/karte-react-native#35]
## Expected Behavior

Successful Android app builds in combination with the latest android sdk modules.

## Current Behavior

Android app build fails when combined with android sdk module released on 9/06/2022

## Possible Solution

It is possible to temporarily avoid this by fixing the version such as 'io.karte.android:notifications:2.8.0' in build.gradle in the @react-native-karte/notification module in node_modules.
However, reinstalling the module recurs the problem.

## Steps to Reproduce

1. install @react-native-karte/notification module
2. build android app
3. we cannt build android app.
4.

## SDK Version

- @react-native-karte/core: 1.1.0
- @react-native-karte/in-app-messaging 1.1.0
- @react-native-karte/notification 1.1.0

## Logs

```
e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
class io.karte.android.notifications.KarteAttributes, unresolved supertypes: io.karte.android.tracking.DTO
```

## Possible Implementation

# UPDATE

This problem also occurs in the variables, and visual-tracking modules.

**Comment by nghia11110** [comment]
same issue :(

**Comment by nghia11110** [comment]
@wasnot  my application key is invalid. let check your application key for fix

**Comment by wasnot** [comment]
@nghia11110
Very sorry.

We are releasing Android SDKs with dependency resolution fixes during the day.

- io.karte.android:notificaions:2.9.1
- io.karte.android:variables:2.3.1
- io.karte.android:visualtracking:2.7.1

Hope this helps or you can give it a try.

However, there were cases where it did not work if the cache remained in the local gradle.
I've tried things like adding `--refresh-dependencies` option to the gradle command.

**Comment by nghia11110** [comment]
@wasnot 
thanks for your reply.
that means i can build with @react-native-karte/notification@1.0 from tomorrow?

**Comment by wasnot** [comment]
@nghia11110 
I'm sorry to reply late.

We have already released a fixed version of the Android module for dependency resolution.
So we expect `@react-native-karte/notification 1.0.0` to be buildable.
We have confirmed this internally, but it would be helpful if you could confirm it in an external environment as well.

In addition, we plan to release the React Native module including recurrence prevention.
If updating the android module did not solve the problem, please wait for the react native module update.

Sorry for the inconvenience.

**Comment by nghia11110** [comment]
@wasnot thanks so much for your support.
I have confirmed buildable with @react-native-karte/notification 1.0.0

**Comment by wasnot** [comment]
@nghia11110 
Thank you for confirming!

Sorry for the inconvenience this time.
I will close this issue.
